### ISSUE TITLE
مشکل آپدیت شدن حروف بلافاصله

### ISSUE THREAD

**Issue by hooh88** [SalmanAA/wordifyfa#4]
سلام
من با استفاده از کد های شما یک رقم را در اینپوت دریافت میکنم و در تگ های اچ تی ام ال نمایش میدهم.
از هر رویدادی استفاده کردم که بتونم حروف رو آپدیت نمایش بدم نشد و یک حرف کمتر نشون میده.
مثلا 55 رو میزنه پنج
چطور میشه این مورد رو درست کرد؟

**Comment by hooh88** [comment]
مشکلم حل شد با یکم تغییر
ممنون

**Comment by SalmanAA** [comment]
لطفا تغییری که دادید رو پول ریکوئست بدید که روی نسخه اصلی اعمال بشه. البته با توضیح
Salman Arab Ameri, Web and Software Developer


On Wednesday, July 19, 2017, 11:25:14 AM GMT+4:30, hooh88 <notifications@github.com> wrote:


مشکلم حل شد با یکم تغییر
ممنون

**Comment by hooh88** [comment]
سلام

من میخاستم به این صورت استفاده کنم:
https://jsfiddle.net/HooHir/LrLtz422/2/

که اشتباهی که کرده بودم از تومان استفاده کردم برای همین صفر میزد و اشتباه از خودم بود
ممنون از نوشتن همچین کد خوبی توی پروژه ازش استفاده کردم.

**Comment by r-obert** [comment]
Can you help me understand Persian. Maybe an online resource?

**Comment by r-obert** [comment]
Should I say Farsi instead? Please advise.

**Comment by SalmanAA** [comment]
Hi dear friend,
you can start learning at this site:
http://www.easypersian.com 

If you have any question about Persian(Farsi), I can help you via email (fanus84@yahoo.com)

wish you luck!
