### ISSUE TITLE
provide npm

### ISSUE THREAD

**Issue by mammad2c** [SalmanAA/wordifyfa#5]
Hi,
thanks for your awesome library,
please provide npm repository

![image](https://user-images.githubusercontent.com/16647736/79410553-00a7e500-7fb6-11ea-85a6-4793dee9a5b5.png)

currently `npm i wordifyfa` not working and we should copy your code directly in the project.
thanks

**Comment by SalmanAA** [comment]
Hi dear friend,I will make an npm package for wordifyfa as soon as possible.Thanks for your attention
Salman Arab Ameri, Web and Software Developer 

    On Thursday, April 16, 2020, 07:44:04 AM GMT+4:30, Mohammad Toosi <notifications@github.com> wrote:  
 
 


Hi,
thanks for your awesome library,
please provide npm repository



currently npm i wordifyfa not working and we should copy your code directly in the project.
thanks

**Comment by SalmanAA** [comment]
now you can use "npm i wordifyfa"
