### ISSUE TITLE
Unable to resolve module 

### ISSUE THREAD

**Issue by mdehghani65** [SalmanAA/wordifyfa#6]
i get the following error while trying to use in React-Native:
 _Error: Unable to resolve module_ 

tried all sorts of things and scripts . no luck

**Comment by SalmanAA** [comment]
I think the error is not caused by "wordifyfa". 
please check this url: https://stackoverflow.com/questions/40985027/unable-to-resolve-module-in-react-native-app
and if you can't solve the problem, send some screenshots of build logs with more information.

**Comment by mdehghani65** [comment]
thx for your response . i tried the solutions before. i decided to use another library
